server:
  port: 80
eureka:
  client:
    register-with-eureka: false
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  instance:
    lease-renewal-interval-in-seconds: 30 #eurekaClient客户端发送心跳的间隔时间；默认为30

# 设置feign客户端超时时间(OpenFeign默认支持ribbon)
ribbon:
  #在com.netflix.client.config.DefaultClientConfigImpl#getProperty(java.lang.String)方法里面，会读取配置文件中配置的ribbon的超时时间，
  #优先使用 服务名.ribbon.ReadTimeout这个配置，如果没有则使用ribbon.ReadTimeout，
  #还没有则使用默认值, ps:ribbon.ReadTimeout和ribbon.ConnectTimeout的默认值都是1000毫秒，
  #连接超时设置1秒钟还好，ReadTimeout一秒钟太短了，需要加大点，不过也要按需调整。
  # 指的是建立连接后从服务器读取到可用资源所用的时间
  ReadTimeout: 2000
  # 指的是建立连接所用的时间,适用于网络状态正常的情况下,两端连接所用的时间
  #ConnectTimeout: 5000
logging: #开启日志功能
  level:
    # feign日志以什么级别监控哪个接口，如果需要监控多个，去掉具体类名，填包名就好了
    com.lv.cloud.service.PaymentService: debug

feign:
  hystrix:
    enabled: true #必须要在客户端开启，在公共包开启没有用
