server:
  port: 80
eureka:
  client:
    register-with-eureka: false
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  instance:
    lease-renewal-interval-in-seconds: 30 #eurekaClient客户端发送心跳的间隔时间；默认为30
spring:
  application:
    name: consumer-order80
  zipkin:
    base-url: http://localhost:9411 #把采集到的数据放在这个zipkin上面展示
  sleuth:
    sampler:
      probability: 1 #采样介于0-1之间，1表示全部采集
